resource "aws_lambda_permission" "allow_sns_invoke" {
  statement_id  = "AllowExecutionFromSNS"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.email_sender.function_name
  principal     = "sns.amazon.com"
  source_arn    = aws_sns_topic.user_signup.arn
}

# package lambda directory
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/../serverless"
  output_path = "{path.module}/dist/email_sender.zip"
  excludes    = ["node_modules", ".git", "dist"]
}

resource "aws_lambda_function" "email_sender" {
  function_name = "email_sender"
  runtime       = "nodejs20.x"
  handler       = "ses_email.handler"                # File name + exported function name
  role          = aws_iam_role.lambda_email_role.arn # IAM role with SES + CloudWatch permissions

  # Use the zip generated by the archive_file data source
  filename = data.archive_file.lambda_zip.output_path

  # Ensures Lambda is automatically updated when the ZIP content changes.
  # Terraform compares this hash to detect code updates.
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256

  # Environment variables available in process.env
  environment {
    variables = {
      FROM_EMAIL      = var.verifiedSenderEmail  # Verified sender email in SES
      VERIFY_URL_BASE = var.verificationEndPoint # Your web app verification endpoint
    }
  }
}
